name: Build

on:
  pull_request:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Install Node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: pnpm install
    - name: Check
      run: pnpm check

  build-extension:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Install Node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm extension:package
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: objdiff-*.vsix
        if-no-files-found: error

  build-web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Install Node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm web:build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: dist
